services:
  jupyter:
    image: jupyter/base-notebook:latest
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_PASSWORD=x
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan

networks:
  default:
    name: my_network
